management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health

forgesync:
  mqtt:
    enabled: false
    server-uri: tcp://localhost:1883
    client-id: forgesync-api-local
